apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patronus-operator.fullname" . }}
  labels:
    {{- include "patronus-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "patronus-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "patronus-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "patronus-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: operator
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PATRONUS_API_URL
          value: {{ .Values.patronus.apiUrl | quote }}
        - name: METRICS_PORT
          value: {{ .Values.metrics.port | quote }}
        - name: RUST_LOG
          value: "info"
        {{- if .Values.leaderElection.enabled }}
        - name: LEADER_ELECTION_ENABLED
          value: "true"
        - name: LEADER_ELECTION_LEASE_DURATION
          value: {{ .Values.leaderElection.leaseDuration | quote }}
        - name: LEADER_ELECTION_RENEW_DEADLINE
          value: {{ .Values.leaderElection.renewDeadline | quote }}
        - name: LEADER_ELECTION_RETRY_PERIOD
          value: {{ .Values.leaderElection.retryPeriod | quote }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
