{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "patronus-operator.fullname" . }}-metrics
  labels:
    {{- include "patronus-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "patronus-operator.selectorLabels" . | nindent 4 }}
{{- end }}
