groups:
  - name: patronus_sdwan_alerts
    interval: 30s
    rules:
      # Service Health Alerts
      - alert: DashboardDown
        expr: up{job="patronus-dashboard"} == 0
        for: 1m
        labels:
          severity: critical
          component: dashboard
        annotations:
          summary: "Patronus Dashboard is down"
          description: "The Patronus Dashboard has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High HTTP error rate detected"
          description: "HTTP error rate is {{ $value | humanizePercentage }} over the last 5 minutes."

      # Authentication Alerts
      - alert: HighLoginFailureRate
        expr: rate(auth_login_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: auth
        annotations:
          summary: "High login failure rate detected"
          description: "Login failure rate is {{ $value }} failures/sec over the last 5 minutes. Possible brute force attack."

      - alert: NoActiveUsers
        expr: active_users_total == 0
        for: 30m
        labels:
          severity: info
          component: auth
        annotations:
          summary: "No active users"
          description: "No users have been active for the last 30 minutes."

      # SD-WAN Network Alerts
      - alert: PathDown
        expr: sdwan_paths_active < sdwan_paths_total * 0.8
        for: 2m
        labels:
          severity: critical
          component: sdwan
        annotations:
          summary: "SD-WAN path degradation"
          description: "Only {{ $value }} of {{ $labels.paths_total }} paths are active."

      - alert: HighPathLatency
        expr: histogram_quantile(0.95, rate(sdwan_path_latency_ms_bucket[5m])) > 100
        for: 5m
        labels:
          severity: warning
          component: sdwan
        annotations:
          summary: "High path latency detected"
          description: "Path {{ $labels.path_id }} has p95 latency of {{ $value }}ms."

      - alert: HighPacketLoss
        expr: sdwan_path_packet_loss_pct > 5
        for: 5m
        labels:
          severity: warning
          component: sdwan
        annotations:
          summary: "High packet loss detected"
          description: "Path {{ $labels.path_id }} has {{ $value }}% packet loss."

      # Database Alerts
      - alert: HighDatabaseQueryTime
        expr: histogram_quantile(0.95, rate(db_query_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Slow database queries"
          description: "Database query p95 latency is {{ $value }}s for {{ $labels.type }}."

      - alert: DatabaseErrors
        expr: rate(db_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "Database errors detected"
          description: "Database error rate is {{ $value }} errors/sec."

      # Performance Alerts
      - alert: HighMemoryUsage
        expr: system_memory_usage_bytes > 1073741824
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanize }}B (>1GB)."

      - alert: SlowHTTPResponses
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "Slow HTTP responses"
          description: "HTTP p95 response time is {{ $value }}s for {{ $labels.path }}."

      # WebSocket Alerts
      - alert: HighWebSocketConnections
        expr: websocket_connections_active > 100
        for: 5m
        labels:
          severity: info
          component: websocket
        annotations:
          summary: "High WebSocket connection count"
          description: "There are {{ $value }} active WebSocket connections."

      # Capacity Planning Alerts
      - alert: HighSiteCount
        expr: sdwan_sites_total > 50
        for: 1h
        labels:
          severity: info
          component: capacity
        annotations:
          summary: "High site count"
          description: "Managing {{ $value }} sites. Consider scaling resources."

      - alert: HighPolicyCount
        expr: sdwan_policies_total > 100
        for: 1h
        labels:
          severity: info
          component: capacity
        annotations:
          summary: "High policy count"
          description: "{{ $value }} policies configured. Review for optimization opportunities."

      # BFD (Bidirectional Forwarding Detection) Alerts
      - alert: BfdSessionDown
        expr: patronus_bfd_session_status{state="down"} == 1
        for: 1m
        labels:
          severity: critical
          component: bfd
        annotations:
          summary: "BFD session down"
          description: "BFD session {{ $labels.session_id }} is down on path {{ $labels.path_id }}."

      - alert: BfdSlowDetection
        expr: patronus_bfd_detection_time_ms > 1000
        for: 2m
        labels:
          severity: warning
          component: bfd
        annotations:
          summary: "BFD slow failure detection"
          description: "BFD detection time is {{ $value }}ms (expected <900ms) on path {{ $labels.path_id }}."

      - alert: BfdHighPacketLoss
        expr: rate(patronus_bfd_packets_lost_total[5m]) / rate(patronus_bfd_packets_sent_total[5m]) * 100 > 10
        for: 3m
        labels:
          severity: warning
          component: bfd
        annotations:
          summary: "High BFD packet loss"
          description: "BFD packet loss is {{ $value | humanizePercentage }} on path {{ $labels.path_id }}."

      # Compression Alerts
      - alert: CompressionDisabled
        expr: patronus_compression_enabled == 0
        for: 5m
        labels:
          severity: info
          component: compression
        annotations:
          summary: "Compression disabled"
          description: "Data compression is disabled on path {{ $labels.path_id }}. Consider enabling for bandwidth savings."

      - alert: LowCompressionRatio
        expr: (1 - (rate(patronus_compression_output_bytes_total[10m]) / rate(patronus_compression_input_bytes_total[10m]))) * 100 < 5
        for: 30m
        labels:
          severity: info
          component: compression
        annotations:
          summary: "Low compression ratio"
          description: "Compression ratio is only {{ $value | humanizePercentage }} on path {{ $labels.path_id }}. Data may not be compressible."

      - alert: CompressionErrors
        expr: rate(patronus_compression_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          component: compression
        annotations:
          summary: "Compression errors detected"
          description: "Compression error rate is {{ $value }} errors/sec on path {{ $labels.path_id }}."

      # Failover Alerts
      - alert: FrequentFailovers
        expr: increase(patronus_failover_count_total[30m]) > 5
        for: 5m
        labels:
          severity: warning
          component: failover
        annotations:
          summary: "Frequent failover events"
          description: "Path {{ $labels.path_id }} has failed over {{ $value }} times in the last 30 minutes. Check network stability."

      - alert: FailoverCooldown
        expr: patronus_failover_cooldown_active == 1
        for: 10m
        labels:
          severity: info
          component: failover
        annotations:
          summary: "Failover in cooldown"
          description: "Failover for path {{ $labels.path_id }} is in cooldown period to prevent flapping."

      # DPI (Deep Packet Inspection) Alerts
      - alert: DpiClassificationFailure
        expr: rate(patronus_dpi_classification_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: dpi
        annotations:
          summary: "DPI classification failures"
          description: "DPI is experiencing {{ $value }} classification errors/sec."

      - alert: DpiLowAccuracy
        expr: (sum(patronus_dpi_classified_flows_total) / sum(patronus_dpi_total_flows_total)) * 100 < 70
        for: 15m
        labels:
          severity: warning
          component: dpi
        annotations:
          summary: "Low DPI classification accuracy"
          description: "DPI classification accuracy is only {{ $value | humanizePercentage }}. Many flows are unclassified."

      - alert: DpiHighUnknownTraffic
        expr: rate(patronus_dpi_bytes_total{app_type="Unknown"}[10m]) / rate(patronus_dpi_bytes_total[10m]) * 100 > 30
        for: 15m
        labels:
          severity: info
          component: dpi
        annotations:
          summary: "High unknown traffic percentage"
          description: "{{ $value | humanizePercentage }} of traffic is unclassified by DPI. Consider updating classifiers."

      # QoS (Quality of Service) Alerts
      - alert: QosBufferOverflow
        expr: increase(patronus_qos_buffer_overflows_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          component: qos
        annotations:
          summary: "QoS buffer overflow"
          description: "QoS class {{ $labels.class }} has {{ $value }} buffer overflows in the last 5 minutes."

      - alert: QosHighDropRate
        expr: rate(patronus_traffic_shaping_drops_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
          component: qos
        annotations:
          summary: "High QoS drop rate"
          description: "QoS class {{ $labels.class }} is dropping {{ $value }} packets/sec due to rate limiting."

      - alert: QosRealtimeLatencyViolation
        expr: histogram_quantile(0.95, rate(patronus_qos_latency_seconds_bucket{class="realtime"}[5m])) * 1000 > 50
        for: 3m
        labels:
          severity: critical
          component: qos
        annotations:
          summary: "RealTime QoS latency violation"
          description: "RealTime traffic p95 latency is {{ $value }}ms (target <50ms)."

      # SLA (Service Level Agreement) Alerts
      - alert: SlaLatencyViolation
        expr: patronus_path_latency_sla_met == 0
        for: 5m
        labels:
          severity: warning
          component: sla
        annotations:
          summary: "SLA latency violation"
          description: "Path {{ $labels.path_id }} is violating latency SLA ({{ $labels.target_latency_ms }}ms)."

      - alert: SlaPacketLossViolation
        expr: patronus_path_packet_loss_sla_met == 0
        for: 5m
        labels:
          severity: warning
          component: sla
        annotations:
          summary: "SLA packet loss violation"
          description: "Path {{ $labels.path_id }} is violating packet loss SLA ({{ $labels.target_loss_pct }}%)."

      - alert: SlaJitterViolation
        expr: patronus_path_jitter_sla_met == 0
        for: 5m
        labels:
          severity: warning
          component: sla
        annotations:
          summary: "SLA jitter violation"
          description: "Path {{ $labels.path_id }} is violating jitter SLA ({{ $labels.target_jitter_ms }}ms)."

      - alert: SlaComplianceLow
        expr: (count(patronus_path_latency_sla_met == 1) / count(patronus_path_latency_sla_met)) * 100 < 95
        for: 15m
        labels:
          severity: critical
          component: sla
        annotations:
          summary: "Low SLA compliance"
          description: "Overall SLA compliance is {{ $value | humanizePercentage }} (target >95%)."
