# Simple Patronus SD-WAN Deployment Example
# Hub-and-Spoke topology with 1 hub and 2 branch sites

deployment:
  name: simple-sdwan
  organization: acme-corp
  version: "1.0"

sites:
  - id: 550e8400-e29b-41d4-a716-446655440000
    name: hq
    location: New York, NY
    address: 10.0.0.1
    enabled: true
    created_at: "2024-01-01T00:00:00Z"

  - id: 550e8400-e29b-41d4-a716-446655440001
    name: branch1
    location: Chicago, IL
    address: 10.0.1.1
    enabled: true
    created_at: "2024-01-01T00:00:00Z"

  - id: 550e8400-e29b-41d4-a716-446655440002
    name: branch2
    location: Los Angeles, CA
    address: 10.0.2.1
    enabled: true
    created_at: "2024-01-01T00:00:00Z"

tunnels:
  - id: tun-001
    name: hq-branch1
    source: hq
    destination: branch1
    protocol: wireguard
    encryption: true
    status: running
    created_at: "2024-01-01T00:00:00Z"

  - id: tun-002
    name: hq-branch2
    source: hq
    destination: branch2
    protocol: wireguard
    encryption: true
    status: running
    created_at: "2024-01-01T00:00:00Z"

policies:
  - id: pol-001
    name: allow-all-internal
    source: 10.0.0.0/8
    destination: 10.0.0.0/8
    action: allow
    priority: 100

  - id: pol-002
    name: deny-external
    source: 10.0.0.0/8
    destination: 0.0.0.0/0
    action: deny
    priority: 200

bgp:
  enabled: false
  asn: null
  router_id: null
  peers: []

monitoring:
  enabled: true
  metrics_port: 9090
  prometheus_endpoint: http://localhost:9090
  grafana_endpoint: http://localhost:3000

qos:
  enabled: true
  classes:
    - name: realtime
      bandwidth_min: 10Mbps
      bandwidth_max: 100Mbps
      priority: 1
    - name: business
      bandwidth_min: 5Mbps
      bandwidth_max: 50Mbps
      priority: 2
    - name: best-effort
      bandwidth_min: 1Mbps
      bandwidth_max: unlimited
      priority: 3
